<?php
// 1. Prevent any accidental output (Fixes "Data already output" error)
ob_start();

// 2. Include FPDF safely using absolute path
require_once __DIR__ . '/fpdf/fpdf.php';
include 'config/db.php';

// 3. Check Plan ID
if(!isset($_GET['id'])){
    die("Invalid Visit Plan ID");
}

$plan_id = intval($_GET['id']);

// 4. Get Visit Plan Details
$plan_sql = "SELECT * FROM visit_plan WHERE plan_id = $plan_id";
$plan_result = mysqli_query($conn, $plan_sql);

if(mysqli_num_rows($plan_result) == 0){
    die("Visit Plan Not Found");
}

$plan = mysqli_fetch_assoc($plan_result);

// 5. Get Places in Plan
$sql = "
    SELECT vpd.visit_order, tp.place_name, c.category_name, tp.distance, tp.opening_hours, tp.address
    FROM visit_plan_details vpd
    JOIN tourist_places tp ON vpd.place_id = tp.place_id
    JOIN categories c ON tp.category_id = c.category_id
    WHERE vpd.plan_id = $plan_id
    ORDER BY vpd.visit_order ASC
";
$result = mysqli_query($conn, $sql);

// 6. Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// Title
$pdf->SetFont('Arial', 'B', 18);
$pdf->SetTextColor(25, 135, 84); // Green color matching your theme
$pdf->Cell(190, 10, 'Local Tourist Day Visit Planner', 0, 1, 'C');

$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(190, 8, 'Visit Plan Report', 0, 1, 'C');
$pdf->Ln(5);

// Visitor Details Box
$pdf->SetFillColor(240, 240, 240);
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(95, 8, ' Visitor Name: ', 1, 0, 'L', true);
$pdf->SetFont('Arial', '', 11);
$pdf->Cell(95, 8, ' ' . $plan['visitor_name'], 1, 1, 'L', true);

$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(95, 8, ' Visit Date: ', 1, 0, 'L', true);
$pdf->SetFont('Arial', '', 11);
$pdf->Cell(95, 8, ' ' . $plan['visit_date'], 1, 1, 'L', true);

$pdf->SetFont('Arial', 'I', 9);
$pdf->Cell(190, 6, 'Generated on: ' . date('d M Y, h:i A'), 0, 1, 'R');
$pdf->Ln(5);

// Table Header
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(25, 135, 84); // Green header
$pdf->SetTextColor(255, 255, 255); // White text

$pdf->Cell(10, 10, 'No', 1, 0, 'C', true);
$pdf->Cell(50, 10, 'Place Name', 1, 0, 'C', true);
$pdf->Cell(35, 10, 'Category', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Distance', 1, 0, 'C', true);
$pdf->Cell(65, 10, 'Opening Hours', 1, 1, 'C', true);

// Table Data
$pdf->SetFont('Arial', '', 9);
$pdf->SetTextColor(0, 0, 0);
$count = 1;
$total_distance = 0;

while($row = mysqli_fetch_assoc($result)){
    // Calculate total distance (floatval handles "14.80 km" -> 14.80)
    $total_distance += floatval($row['distance']);
    
    $pdf->Cell(10, 10, $count, 1, 0, 'C');
    $pdf->Cell(50, 10, substr($row['place_name'], 0, 25), 1, 0, 'L');
    $pdf->Cell(35, 10, substr($row['category_name'], 0, 18), 1, 0, 'L');
    $pdf->Cell(30, 10, $row['distance'] . ' km', 1, 0, 'C');
    $pdf->Cell(65, 10, substr($row['opening_hours'], 0, 30), 1, 1, 'L');
    
    $count++;
}

// Total Distance Summary
$pdf->Ln(5);
$pdf->SetFont('Arial', 'B', 11);
$pdf->SetFillColor(255, 243, 205); // Light yellow background for summary
$pdf->Cell(125, 10, ' Total Estimated Distance for this Trip:', 1, 0, 'R', true);
$pdf->Cell(65, 10, number_format($total_distance, 2) . ' km', 1, 1, 'C', true);

// Footer
$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 9);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(190, 10, 'Generated by Local Tourist Day Visit Planner | Eravur, Batticaloa', 0, 1, 'C');

// 7. Clear buffer and Download PDF
ob_end_clean(); 
$pdf->Output('D', 'Visit_Plan_' . $plan_id . '.pdf');
exit; // Stop execution immediately after download
?>